/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_chorus_free: (a: number, b: number) => void;
export const __wbg_hardclip_free: (a: number, b: number) => void;
export const chorus_get_base_delay_ms: (a: number) => number;
export const chorus_get_depth_ms: (a: number) => number;
export const chorus_get_feedback: (a: number) => number;
export const chorus_get_mix: (a: number) => number;
export const chorus_get_rate_hz: (a: number) => number;
export const chorus_new: (a: number, b: number, c: number, d: number, e: number, f: number) => number;
export const chorus_process: (a: number, b: number, c: number, d: any) => void;
export const chorus_set_base_delay_ms: (a: number, b: number) => void;
export const chorus_set_depth_ms: (a: number, b: number) => void;
export const chorus_set_feedback: (a: number, b: number) => void;
export const chorus_set_mix: (a: number, b: number) => void;
export const chorus_set_rate_hz: (a: number, b: number) => void;
export const dsp_version: () => [number, number];
export const hardclip_get_drive: (a: number) => number;
export const hardclip_get_gain: (a: number) => number;
export const hardclip_new: (a: number, b: number) => number;
export const hardclip_process: (a: number, b: number, c: number, d: any) => void;
export const hardclip_set_drive: (a: number, b: number) => void;
export const hardclip_set_gain: (a: number, b: number) => void;
export const onepolelowpass_new: (a: number, b: number) => number;
export const onepolelowpass_set_cutoff: (a: number, b: number, c: number) => void;
export const os_version: () => [number, number];
export const softclip_process: (a: number, b: number, c: number, d: any) => void;
export const softclip_new: (a: number, b: number) => number;
export const __wbg_onepolelowpass_free: (a: number, b: number) => void;
export const __wbg_softclip_free: (a: number, b: number) => void;
export const softclip_get_gain: (a: number) => number;
export const softclip_get_drive: (a: number) => number;
export const softclip_set_gain: (a: number, b: number) => void;
export const softclip_set_drive: (a: number, b: number) => void;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_start: () => void;
